### ISSUE TITLE
オラッ

### ISSUE THREAD

**Issue by Everysick** [opentie/opentie-app#17]
- [x] GET        /api/v1/dashboard(.:format)
- [x] GET        /api/v1/register/new(.:format)
- [x] POST        /api/v1/register/validate(.:format)
- [x] POST       /api/v1/register(.:format)
- [x] POST       /api/v1/projects(.:format)
- [x] POST       /api/v1/projects/validate(.:format)
- [x] GET        /api/v1/projects/new(.:format)
- [x] GET        /api/v1/projects/:id/edit(.:format)
- [x] GET        /api/v1/projects/:id(.:format)
- [x] PUT        /api/v1/projects/:id(.:format)
- [x] GET    /projects/:project_id/invitations/new(.:format)
- [x] POST    /projects/:project_id/invitations(.:format)
- [x] DELETE /projects/:project_id/invitations/:id(.:format)
- [x] GET        /api/v1/projects/:project_id/request_schemata(.:format)
- [x] GET        /api/v1/projects/:project_id/request_schemata/:id(.:format)
- [x] POST       /api/v1/projects/:project_id/request_schemata/:request_schema_id/request(.:format)
- [x] POST       /api/v1/projects/:project_id/request_schemata/:request_schema_id/request/validate(.:format)
- [x] GET        /api/v1/projects/:project_id/request_schemata/:request_schema_id/request/new(.:format)
- [x] GET        /api/v1/projects/:project_id/request_schemata/:request_schema_id/request/edit(.:format)
- [x] GET        /api/v1/projects/:project_id/request_schemata/:request_schema_id/request(.:format)
- [x] PUT        /api/v1/projects/:project_id/request_schemata/:request_schema_id/request(.:format)
- [x] DELETE     /api/v1/projects/:project_id/request_schemata/:request_schema_id/request(.:format)
- [x] GET        /api/v1/divisions/:id(.:format)
- [x] GET        /api/v1/divisions/:division_id/projects(.:format)
- [x] GET        /api/v1/divisions/:division_id/projects/:id(.:format)
- [x] GET        /api/v1/divisions/:division_id/projects/:project_id/requests(.:format)
- [x] GET        /api/v1/divisions/:division_id/projects/:project_id/requests/:id(.:format)
- [x] GET        /api/v1/divisions/:division_id/request_schemata(.:format)
- [x] GET        /api/v1/divisions/:division_id/request_schemata/:id(.:format)
- [x] GET        /api/v1/divisions/:division_id/request_schemata/:request_schema_id/requests(.:format)
- [x] GET        /api/v1/divisions/:division_id/request_schemata/:request_schema_id/requests/:id(.:format)
- [x] GET        /api/v1/divisions/:division_id/project_histories(.:format)
- [x] POST       /api/v1/login(.:format)
- [x] POST       /api/v1/logout(.:format)

**Comment by polamjag** [comment]
お疲れ様でした
