### ISSUE TITLE
ライセンスが明記されてない

### ISSUE THREAD

**Issue by KOBA789** [opentie/opentie-app#2]
GPLv3 がいいです!

**Comment by KOBA789** [comment]
委員長に相談だな

**Comment by KOBA789** [comment]
そういえば趣味でやってるものなのでなんでもいい気がした

**Comment by KOBA789** [comment]
app は各学園祭のビジネスロジックが含まれることが予想されるので MIT にしておかないとこれを元に作った app を全部公開しなくちゃいけなくなってダルい。MIT

**Comment by polamjag** [comment]
:+1: :naruhodori: :+1:

**Comment by KOBA789** [comment]
fixed in #bd8539d283ca78172a19563428a04e881c27db60
